server:
  port: 8008
  servlet:    context-path: /info
spring:  devtools:    restart:      enabled: true
  datasource:    url: jdbc:mysql://localhost:3306/contract?characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: 1234
    driver-class-name:  com.mysql.cj.jdbc.Driver
  thymeleaf:
   cache: false
   prefix: classpath:/templates/
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: HTML5

mybatis:
  type-aliases-package: com.example.demo.model  mapper-locations: classpath:mapper/*.xml
  
